### PR TITLE
237 footer redesign

### PR DESCRIPTION
**Pull request by TP15**
I'm not 100% sure if the space between the icons and the text is enough. If there is a problem just text me:)

### CODE REVIEW

**Comment by olehoef** [comment]
Thanks for your pr.

I think the space in between is fine but the logos look quite large to me but it's in accordance with the design. @jazzjacob is this supposed to look like that?

image

**Comment by jazzjacob** [comment]
Stuff to fix:
- [ ] Use typeface: work sans
- [ ] Smaller size/scale (see image or figma)
- [ ] Add the gradient line (works like a border top)
- [ ] Use icons as components (found in components/icons)
- [ ] Nothing hardcoded - links, text (add necessary text/links in en.json and sv.json in /locals)
- [ ] Bigger space between icons and address

Sorry for not making the scale more clear

size

**Comment by jazzjacob** [comment]
Took the liberty to fix the stuff myself. @olehoef take a look and merge if you approve

**Review by olehoef — APPROVED** [review]
looks great!!

**Pull request merged**
