### PR TITLE
266-fast-track-landing-page

### PR DESCRIPTION
**Pull request by olehoef**
I updated the landing page and the about page as per the design. I also changed the routing for the catalog. 

Maybe we can discuss it in detail tomorrow.

### CODE REVIEW

**Comment by olehoef** [comment]
- [ ] hero button link (should link to /companies)
- [ ] partners: confirm final list
- [ ] banner (mobile): make bigger
- [ ] Blog: implement new blog post
- [ ] Picture buttons (bottom): hover effect
- [ ] add full-size images
- [ ] banner: make clickable 
- [ ] /companies: change text a bit
- [ ] add old cat notice
- [ ] Landing: Gradient line under banner images in CSS

**Comment by olehoef** [comment]
is there anything missing for now? Otherwise I would change the target branch to master so we get a preview.

**Comment by jazzjacob** [comment]
I'd just like to fine tune the styling for the countdown

**Comment by jazzjacob** [comment]
> is there anything missing for now? Otherwise I would change the target branch to master so we get a preview.

I am ready!

**Review by jazzjacob — DISMISSED** [review]

**Comment by olehoef** [comment]
isn't the countdown on mobile a little small now? I mean the numbers?

**Comment by jazzjacob** [comment]
> isn't the countdown on mobile a little small now? I mean the numbers?

Yeah, I guess we can increase the size of the digits for mobile size.

**Comment by jazzjacob** [comment]
I'm noticing a few issues in safari on my mac and phone, so I gonna need to fix them

**Review by olehoef — COMMENTED** [review]
I somehow miss the slashes in the logo (//)...

**Review by jazzjacob — APPROVED** [review]
I am ready for release now!

**Pull request merged**
